### ISSUE TITLE
walidacja drop down przy kliknieciu zglos samochod do naprawy i w oknie walidacja drop down pokaz historie samochodu

### ISSUE THREAD

**Issue by gajdboll** [kaszaninho/autoserwis#39]
![image](https://github.com/kaszaninho/autoserwis/assets/22726991/e97f6ed0-96fb-4ae0-aaf6-981d90b31704)
pokaz historie samochodu
![image](https://github.com/kaszaninho/autoserwis/assets/22726991/e632623a-e3ef-4ae2-8342-2285a54d5c32)

**Comment by kaszaninho** [comment]
Walidacja w Pojazdach w drop down w wybierz samochod - zrobiona
Walidacja przy wyborze serwisu - nie zroziona - problem z wejsciem na pierwsza stronę.
