### ISSUE TITLE
Cennik - traktować osobno

### ISSUE THREAD

**Issue by kaszaninho** [kaszaninho/autoserwis#9]
Na początku warto zaznaczyć, że wstępnie będę analizował poszczególne elementy od strony ADMINA, gdyż on będzie miał największe uprawnienia na stronie. W ten sposób najłatwiej będzie to przeanalizować, a wersje dla klientów otrzymamy poprzez ograniczenie wersji Adminowskiej.
Przykład - cennik:

![image](https://github.com/kaszaninho/autoserwis/assets/104163637/a5cc6766-62fe-450e-8a4d-2412a541362e)

Tak wygląda cennik w wersji z zeszłego semestru. Biorąc pod uwagę, że mamy dodany osobny model 'TypySerwisu', który właśnie ma odzwierciedlać ten widok, to można potraktowac jako osobny element oraz jest bardzo podobny do przykładów z zajęć jak przedmioty czy studenci - można na nich bazować.
Czyli utworzyć podstrony 'cennika', które będą odpowiadały za dodawanie, edycję oraz usuwanie oraz zapewnic logikę biznesową w kontrolerze.

**Comment by gajdboll** [comment]
@kaszaninho Problem czesciowo rozwiazany - funkcje wszystkei zaimplementowane lecz podczas tworzenia lub edycji layout nie jest dziedziczony
![image](https://github.com/kaszaninho/autoserwis/assets/22726991/b6524819-aeca-4609-ac35-d464f888b4cc)
Branch: kgajdosz/cennik
